# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Vincentqyw"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Depth Estimation":
        filters: ["Depth Estimation", "Monocular Depth Estimation", "Stereo Matching", "Multi-View Stereo"]
    "Eye Tracking":
        filters: ["Eye Tracking", "Gaze Estimation"]
    "Gesture Recognition":
        filters: ["Gesture Recognition", "Hand Tracking", "Gesture Classification"]
    "Image Matching":
        filters: ["Keypoint Detection", "Feature Descriptor", "Image Matching", "Keypoint Matching", 
                  "Line Segment Detection", "Local Feature Matching"]
    "Embodied AI":
        filters: [
            "Multimodal Models", "Multi-Modal Large Language Model", "Embodied Perception", 
            "Multimodal Interaction", "Vision Language Model", "VLM", "Embodied Large Language Model", "Embodied LLM",
        ]
    "Diffusion":
        filters: ["Diffusion", "Diffusion Models", "Text to 3D", "Image to 3D"]
    "NeRF":
        filters: ["NeRF", "Neural Radiance Fields", "SDF", "Signed Distance Funciton"]
    "Gaussian Splatting":
        filters: ["Gaussian Splatting", "3D Gaussian Splatting", "3D GS"]