"""Shared limits for local paper-model requests."""

DEFAULT_MODEL = "PaperReader-Qwen3.8"
DEFAULT_MODEL_TIMEOUT_SECONDS = 900
DEFAULT_MODEL_WORKERS = 4
DEFAULT_MODEL_MAX_TOKENS = 8192
MAX_MODEL_WORKERS = 32
