title: Arxiv Papers Daily
description: Update Arxiv Papers Daily using Github Actions
show_downloads: true

github:
  zip_url: https://github.com/zyf515730395/arxiv-papers-daily
  another_url: https://github.com/zyf515730395/arxiv-papers-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: zyf515730395

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-toc